### ISSUE TITLE
index.ipynb not found

### ISSUE THREAD

**Issue by jpetoskey** [learn-co-curriculum/dsc-running-jupyter-locally-lab#1]
I think I followed all of the steps correctly to open my Jupyter notebook locally, but I could not find the index.ipynb file -- it is not in the files for this lesson so I'm wondering what went wrong?  Thank you!

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by ismayc** [comment]
Hi there. I suspect you've already figured this out, but just in case, the index.ipynb file is available in this repo [here](https://github.com/learn-co-curriculum/dsc-running-jupyter-locally-lab/blob/master/index.ipynb). It will be in the main directory after you clone the repo down to your computer.
